"""Local end-to-end: real Fortran integration + real adelie solve through
the driver loop, no mocks, no Slurm (LocalRunner executes task scripts).

Uses the tiny NGC6278 example system (nE=3 orblib) so a full
propose->integrate->solve->observe->exhaust cycle costs seconds of CPU -
safe alongside production. Nothing touches PM_grid or any live tree.
"""

import os
import shutil
import sys

import pytest
import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

pytestmark = pytest.mark.local_slow

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
NGC6278_INPUT = os.path.join(REPO, "dev_tests", "NGC6278_input")
STOCK_CONFIG = os.path.join(REPO, "dev_tests", "test_slurm_config.yaml")


@pytest.fixture()
def sandbox(tmp_path):
    inp = tmp_path / "NGC6278_input"
    shutil.copytree(NGC6278_INPUT, inp)
    out = tmp_path / "NGC6278_output"
    out.mkdir()

    with open(STOCK_CONFIG) as f:
        cfgd = yaml.safe_load(f)

    cfgd["legacy_settings"]["directory"] = os.path.join(REPO, "legacy_fortran")
    ws = cfgd["weight_solver_settings"]
    ws["type"] = "NNLS"
    ws["nnls_solver"] = "adelie"
    ws["nnls_dtype"] = "float32"
    ws["stream_orblib_reads"] = True
    ws.setdefault("reattempt_failures", True)
    ms = cfgd["multiprocessing_settings"]
    ms["modeliterator"] = "SplitModelIterator"
    ms["ncpus"] = 4
    ms["orblibs_in_parallel"] = False
    ps = cfgd["parameter_space_settings"]
    ps["generator_type"] = "GridWalk"
    sc = ps["stopping_criteria"]
    sc["n_max_mods"] = 2
    cfgd["io_settings"]["input_directory"] = str(inp)
    cfgd["io_settings"]["output_directory"] = str(out)

    cfg_path = tmp_path / "vera_e2e.yaml"
    with open(cfg_path, "w") as f:
        f.write("# local e2e sandbox - generated by test_vera_e2e_local.py\n")
        yaml.safe_dump(cfgd, f, sort_keys=False)

    run_dir = tmp_path / "run"
    run_dir.mkdir()
    return {
        "tmp": tmp_path,
        "config": str(cfg_path),
        "outroot": str(out),
        "run_dir": str(run_dir),
    }


def _make_driver(sandbox):
    import dynamite as dyn
    from dynamite.vera.driver import VeraDriver
    from dynamite.vera.local_runner import LocalRunner
    from dynamite.vera.proposer_gridwalk import GridWalkProposer

    cwd = os.getcwd()
    os.chdir(sandbox["run_dir"])
    try:
        c = dyn.config_reader.Configuration(sandbox["config"], reset_logging=True)
    finally:
        os.chdir(cwd)
    runner = LocalRunner(
        env={
            "VERA_CONFIG": sandbox["config"],
            "VERA_RUN_DIR": sandbox["run_dir"],
            # subprocesses must see the slurm-branch checkout, not the older
            # site-packages install that the live production grid uses
            "PYTHONPATH": REPO,
        }
    )
    return VeraDriver(
        c, GridWalkProposer(c), runner=runner, run_dir=sandbox["run_dir"]
    ), runner


def test_closed_loop_real_machinery(sandbox):
    drv, runner = _make_driver(sandbox)

    for i in range(8):  # bounded; exhausts well before
        alive = drv.step(dry_run=False)
        t = drv.config.all_models.table
        done = int(sum(1 for r in t if bool(r["all_done"])))
        if not alive or done >= 2:
            break

    t = drv.config.all_models.table
    done_rows = [r for r in t if bool(r["all_done"])]
    assert len(done_rows) >= 2, f"expected >=2 completed models after loop; table:\n{t}"
    for r in done_rows:
        assert r["chi2"] == r["chi2"] and r["chi2"] > 0  # finite positive
        mdir = os.path.join(sandbox["outroot"], "models", r["directory"])
        assert os.path.isfile(os.path.join(mdir, "datfil", "tube_box_done"))
        wfile = os.path.join(mdir, "orbit_weights.ecsv")
        assert os.path.isfile(wfile)

    # every submission went through the very scripts slurm will call
    kinds = [os.path.basename(script) for script, _ in runner.executed]
    assert "solve_task.sh" in kinds
    assert "integrate_package.sh" in kinds
    assert drv.exhausted()


def test_dry_run_plan_then_zero_sideeffects(sandbox, capsys):
    drv, runner = _make_driver(sandbox)
    drv.step(dry_run=True)
    out = capsys.readouterr().out
    assert "[dry-run]" in out
    # nothing materialized in the output tree besides the table write
    models_root = os.path.join(sandbox["outroot"], "models")
    created = [d for d in os.listdir(models_root) if d.startswith("orblib_")]
    for d in created:
        assert not os.path.exists(os.path.join(models_root, d, "datfil"))
